# -*- coding: utf-8 -*-
"""Project_01(Simple Chatty Bot).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lJZSXr4nJabgnkR6Nw4NnPSyApcmcz1R
"""

def greet(bot_name, birth_year):
    print('Hello! My name is ' + bot_name + '.')
    print('I was created in ' + birth_year + '.')


def remind_name():
    print('Please, remind me your name.')
    name = input()
    print('What a great name you have, ' + name + '!')


def guess_age():
    print('Let me guess your age.')
    print('Enter remainders of dividing your age by 3, 5 and 7.')

    rem3 = int(input())
    rem5 = int(input())
    rem7 = int(input())
    age = (rem3 * 70 + rem5 * 21 + rem7 * 15) % 105

    print("Your age is " + str(age) + "; that's a good time to start programming!")


def count():
    print('Now I will prove to you that I can count to any number you want.')

    num = int(input())
    curr = 0
    while curr <= num:
        print(curr, '!')
        curr = curr + 1


def test():
    print("Let's test your programming knowledge.")
    # write your code here
    name=input()
    list1=[]
    for i in range(4):
        option=input()
        number=int(input())
        print(number,'.',option)
        num1=int(input())
        if num1!=2:
            print('Please, try again.')
        else:
            pass
    print('Completed, have a nice day!')
def test():
    print("Let's test your programming knowledge.")
    # write your code here
    name=input()
    list1=[]
    for i in range(4):
        option=input()
        number=int(input())
        print(number,'.',option)
    num1=int(input())
    if num1!=2:
        print('Please, try again.')
    else:
        pass

def end():
    print('Congratulations, have a nice day!')


greet('Aid', '2020')  # change it as you need
remind_name()
guess_age()
count()
# ...
test()
end()